[[servers]]
  Address = "tcp://78.46.227.60:7770"
  Public = "5eI+WFOaCdMhHY+g+zR11IZV4MBtg+k8jm59FqqHwQY="
  Description = "Ineiti's Cothority-server"

[[servers]]
  Address = "tcp://192.33.210.8:7770"
  Public = "A2vzFuHqbn6Z4LtxNBnRbAtnlL+dxELMTPNsP5Nek88="
  Description = "EPFL Cothority-server"

[[servers]]
  Address = "tcp://5.135.161.91:2000"
  Public = "KZDPdzN5wlBsFmtmKoc21BTI+fBMbPfYJLf9P11Ur4s="
  Description = "Nikkolasg's powering up CoSi"

[[servers]]
  Address = "tcp://185.26.156.40:61117"
  Public = "m1T9+7OROPCkWgjhchq06yV+DyRsk6JyFU1lFFR1YpA="
  Description = "Ismail's server"